FORMAT: 1A
HOST: https://pay.unipagos.com/

# mydemo

Polls is a simple API allowing consumers to view polls and vote in them.

## Transfers [/transfers]

### Money Transfer [POST]

+ Request (application/json)
    + Headers

            Accept: application/json
            Accept-Language: es-MX
            
    + Body       
    
            {
              "to": {
                "type": "mdn",
                "key": "525500000001"
              },
              "amount": "20",
              "force": true,
              "requestId": "53f28bea6c8761b24d00572d",
              "description": "test transfer #1"
            }

+ Response 200 (application/json)

        [
            {
              "receipt": {
                "id": "50462496-708f-413a-84f3-a1edc876483b",
                "type": "T",
                "create_time": "2014-06-30 10:24:53.527884-05",
                "status": "C",
                "status_time": "2014-06-30 10:24:53.527884-05",
                "description": "test transfer #1",
                "amount": "20.00",
                "currency_code": "MXN",
                "from": {
                  "type": "mdn",
                  "key": "525512257935"
                },
                "to": {
                  "type": "mdn",
                  "key": "525566952123"
                }
              },
              "upOperationId": "20190716-215909-620-0570-0536",
              "_resultCode": "000",
              "_resultType": "SUCCESS",
              "_resultDesc": "operation successful",
              "_message": "Success"
            }
        ]